# Generated by Django 5.2.7 on 2025-10-02 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwisko', models.CharField(max_length=20)),
                ('imie', models.CharField(max_length=20)),
                ('miasto', models.CharField(default='Białystok', max_length=30)),
                ('ulica', models.CharField(max_length=20)),
                ('wiek', models.IntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='date published')),
                ('zalecenia', models.CharField(max_length=200)),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.pacjent')),
            ],
        ),
    ]
